Repository MIT-Emerging-Talent/ET6-foundations-group-09, pull requests merged in 2025-01, with the labels that each got.

#32 Challenge/celsius to fahrenheit
  solutions/celsius_to_fahrenheit.py
  solutions/tests/test_celsius_to_fahrenheit.py
Labels: challenge

#29 Challenge/longest_substring
  solutions/longest_substring.py
  solutions/tests/test_longest_substring.py
Labels: challenge

#37 challenge/find_two_sum_indices
  solutions/find_two_sum_indices.py
  solutions/tests/test_find_two_sum_indices.py
Labels: challenge

#27 challenge/reverse_string
  solutions/reverse_string.py
  solutions/tests/test_reverse_string.py
Labels: challenge

#45 deleted duplicates in Challenge/letter combinations
  .github/PULL_REQUEST_TEMPLATE.md
  solutions/phone_letter_combinations.py
  solutions/tests/test_phone_letter_combinations
Labels: enhancement

#49 formatting error solved
  .github/workflows/ci-checks.yml
  solutions/find_two_sum_indices.py
Labels: enhancement

#50 Challenge/even numbers
  solutions/add_numbers.py
  solutions/even_numbers.py
  solutions/tests/test_add_numbers.py
  solutions/tests/test_even_numbers.py
Labels: challenge

#53 adding challenge/longest_substring
  .vscode/settings.json
Labels: enhancement

#55 added longest substring challenge again
  solutions/longest_substring.py
  solutions/tests/test_longest_substring.py
Labels: duplicate

#57 Retrospective
  collaboration/retrospective.md
Labels: documentation

#58 collaboration file final update
  collaboration/communication.md
  collaboration/groupnorms.md
Labels: documentation

#67 Challenge/celsius to fahrenheit
  solutions/celsius_to_fahrenheit.py
  solutions/tests/test_celsius_to_fahrenheit.py
Labels: challenge

#60 challenge/adding_ascending_numbers
  solutions/ascending_numbers.py
  solutions/tests/test_ascending_numbers.py
Labels: challenge

#70 challenge/weather_conditions
  solutions/tests/test_weather_conditions.py
  solutions/weather_conditions.py
Labels: duplicate

#63 challenge/calculate_grade
  solutions/calculate_grade.py
  solutions/tests/test_calculate_grade.py
Labels: challenge

#71 challenge/count _characters
  solutions/count_characters.py
  solutions/tests/test_count_characters.py
Labels: challenge

#73 Challenge/strong password
  solutions/tests/test_weather_conditions.py
  solutions/weather_conditions.py
Labels: duplicate
